parameters:
#    produit_category.example.class: Produit\CategoryBundle\Example

services:
#    produit_category.example:
#        class: %produit_category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
