produit_category:
    resource: "@ProduitCategoryBundle/Resources/config/routing.yml"
    prefix:   /

ProduitCategoryBundle_produit:
    resource: "@ProduitCategoryBundle/Resources/config/routing/produit.yml"
    prefix:   /produit

ProduitCategoryBundle_category:
    resource: "@ProduitCategoryBundle/Resources/config/routing/category.yml"
    prefix:   /category

